const CONFIG = {
  github: {
    username: 'Temoor-49',
  },
  base: '/',
  projects: {
    github: {
      display: true,
      header: 'Github Projects',
      mode: 'automatic',
      automatic: {
        sortBy: 'stars',
        limit: 8,
        exclude: {
          forks: false,
          projects: [],
        },
      },
      manual: {
        projects: [],
      },
    },
    external: {
      header: 'My Projects',
      projects: [
        {
          title: 'Paraiso',
          description: 'Designed and implemented a three-tier platform with customer, restaurant, and admin functionalities. Integrated features include reservations, pick-up orders, a reward system, and sharing it with friends.',
          imageUrl: 'Paraiso.png',
          link: 'https://github.com/Temoor-49/Paraiso-Project',
        },
        {
          title: 'Little Lemon',
          description: 'A React Native mobile app for the Little Lemon restaurant. Displays menu items, supports search, filtering, and SQLite database storage.',
          imageUrl: 'logo.jpg',
          link: 'https://github.com/Temoor-49/little-lemon-capstone',
        },
        {
          title: 'Portfolio',
          description: 'My personal portfolio website built with React.js to showcase my skills, projects, and experience.',
          imageUrl: 'pf2.jpg',
          link: 'https://github.com/Temoor-49/Temoor-Portfolio.git',
        },
      ],
    },
  },
  seo: {
    title: 'Temoor Hussain',
    description: 'Software Engineer',
    imageURL: '',
  },
  social: {
    linkedin: 'temoor-hussain-812429229',
    x: '@Temor_Husain48',
    researchGate: 'temoor-hussain',
    facebook: 'Temoor Hussain',
    instagram: 'temoor_hussain_',
    reddit: 'temor-49',
    dribbble: 'temoorh',
    behance: 'Temoor Hussain',
    medium: '@temorhusain',
    dev: '@temorhusain',
    stackoverflow: 'temoor-hussain',
    website: 'https://temoor.dev',
    phone: '+92-314-*******',
    email: 'temoorh48@gmail.com',
  },
  resume: {
    fileUrl: 'public/resume.pdf',
  },
  skills: [
    'HTML/CSS',
    'JavaScript',
    'React',
    'React Native',
    'Redux',
    'Firebase',
    'python(numpy, pandas, tensorflow)',
    'data visualization',
    'Project Management',
    'SQA Automation (manual+Automated)',
    'Business Engineer',
    'Operation Analyst',
    'Git',
    'CI/CD',
    'IT Support',  
  ],
  experiences: [
    {
      company: 'Digital Tactics',
      position: 'Software Engineer',
      from: 'Aug 2024',
      to: 'Nov 2024',
      companyLink: 'https://www.thedigitaltactics.com/',
    },
    {
      company: 'Vigorous Technologies',
      position: 'Software Engineer',
      from: 'Dec 2024',
      to: 'Aug 2025',
      companyLink: 'https://vigoroustechnologies.com/',
    },
  ],
  certifications: [
    {
      name: 'Front-End Development',
      body: 'Meta Front-End Certificate',
      year: '2025',
      link: 'https://coursera.org/share/06211e3fef4920452f23e4405ffde72d',
    },
     {
      name: 'Front-End Developer',
      body: 'Front-End Developer(React)',
      year: '2025',
      link: 'https://www.hackerrank.com/certificates/290320dd3ace',
    },
    {
      name: 'Project Management Tools Techniques and Agile Frameworks',
      body: 'Coursera Certificate',
      year: '2024',
      link: 'https://coursera.org/share/529e5c8c62aefca7275241cc7ad4af5c',
    },
    {
      name: 'Microsoft IT support Specialist',
      body: 'IT Specialist Certificate',
      year: '2025',
      link: 'https://coursera.org/share/0631ffe14d9e90b44541c70bfae440db',
    },
    {
      name: 'Google IT Automation with Python',
      body: 'Coursera Certificate',
      year: '2025',
      link: 'https://coursera.org/share/3eeb31f2f7b8972f3a3ab39c6591b2ef',
    },
  ],
  educations: [
    {
      institution: 'Quaid-i-Azam University',
      degree: "Bachelor's in IT",
      from: '2020',
      to: '2024',
    },
    {
      institution: 'Punjab College',
      degree: 'Intermediate in Pre-Engineering',
      from: '2017',
      to: '2019',
    },
  ],
  publications: [
    {
      title: 'Efficient Web Development Techniques',
      conferenceName: '',
      journalName: 'Journal of Web Development',
      authors: 'Temoor Hussain',
      link: 'https://example.com/publication1',
      description: 'This paper discusses modern web development practices including React and React Native for responsive design and optimized performance.',
    },
    {
      title: 'Mobile App Optimization Strategies',
      conferenceName: 'International Mobile Dev Conference',
      journalName: '',
      authors: 'Temoor Hussain',
      link: 'https://example.com/publication2',
      description: 'Study on enhancing mobile app performance and user experience through effective use of React Native and SQLite.',
    },
  ],
 blog: {
  display: false,
},
  googleAnalytics: {
    id: 'G-XXXXXXXXXX',
  },
 hotjar: {
  id: '',
},
  themeConfig: {
    defaultTheme: 'lofi',
    disableSwitch: false,
    respectPrefersColorScheme: false,
    displayAvatarRing: true,
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
      'caramellatte',
      'abyss',
      'silk',
      'procyon',
    ],
  },
  footer: `Made with <a class="text-primary" href="Temoor-49" target="_blank" rel="noreferrer">GitProfile</a> and ❤️`,
  enablePWA: true,
};

export default CONFIG;